[versions]
kotest = "5.6.1"
klang = "1.0.0-SNAPSHOT"
jna = "5.13.0"

[libraries]
kotest = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }

[plugins]
klang = { id = "io.ygdrasil.klang", version.ref = "klang" }